"""Corrigir backref em Produto

Revision ID: 866a8b7f8c6c
Revises: 054fb6e0577a
Create Date: 2023-11-15 01:30:11.994210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866a8b7f8c6c'
down_revision = '054fb6e0577a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
